"""add_doctor_profile_fields

Revision ID: 1d7dafaac16d
Revises: c3b7c2f8e1a2
Create Date: 2026-01-20 16:56:35.670172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1d7dafaac16d'
down_revision: Union[str, Sequence[str], None] = 'c3b7c2f8e1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('specialty', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('room_label', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('availability_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'availability_status')
    op.drop_column('users', 'room_label')
    op.drop_column('users', 'department')
    op.drop_column('users', 'specialty')
    # ### end Alembic commands ###
