"""add patient fields including gender

Revision ID: 71540f7a0ab0
Revises: ea00d335a74e
Create Date: 2025-12-31 22:15:57.507583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71540f7a0ab0'
down_revision: Union[str, Sequence[str], None] = 'ea00d335a74e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS idempotency_keys")
    op.execute("DROP TABLE IF EXISTS dispensations")
    op.execute("DROP TABLE IF EXISTS lab_results")
    op.execute(f"DROP INDEX IF EXISTS {op.f('ix_visit_status_history_visit_id')}")
    op.execute("DROP TABLE IF EXISTS visit_status_history")
    if op.get_bind().dialect.name == "sqlite":
        with op.batch_alter_table("patients") as batch:
            batch.add_column(sa.Column("full_name", sa.String(length=255), nullable=False))
            batch.add_column(sa.Column("phone_number", sa.String(length=20), nullable=False))
            batch.add_column(sa.Column("occupation", sa.String(length=100), nullable=False))
            batch.drop_column("first_name")
            batch.drop_column("phone")
            batch.drop_column("email")
            batch.drop_column("last_name")
    else:
        op.add_column("patients", sa.Column("full_name", sa.String(length=255), nullable=False))
        op.add_column("patients", sa.Column("phone_number", sa.String(length=20), nullable=False))
        op.add_column("patients", sa.Column("occupation", sa.String(length=100), nullable=False))
        op.drop_constraint(op.f("patients_email_key"), "patients", type_="unique")
        op.drop_column("patients", "first_name")
        op.drop_column("patients", "phone")
        op.drop_column("patients", "email")
        op.drop_column("patients", "last_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('patients', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('patients', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('patients_email_key'), 'patients', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('patients', 'occupation')
    op.drop_column('patients', 'phone_number')
    op.drop_column('patients', 'full_name')
    op.create_table('visit_status_history',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('visit_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('from_status', postgresql.ENUM('REGISTERED', 'TRIAGED', 'IN_CONSULTATION', 'LAB_REQUESTED', 'LAB_COMPLETED', 'PHARMACY_PENDING', 'COMPLETED', 'CANCELLED', name='visitstatus'), autoincrement=False, nullable=False),
    sa.Column('to_status', postgresql.ENUM('REGISTERED', 'TRIAGED', 'IN_CONSULTATION', 'LAB_REQUESTED', 'LAB_COMPLETED', 'PHARMACY_PENDING', 'COMPLETED', 'CANCELLED', name='visitstatus'), autoincrement=False, nullable=False),
    sa.Column('changed_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('visit_status_history_changed_by_fkey')),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], name=op.f('visit_status_history_visit_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('visit_status_history_pkey'))
    )
    op.create_index(op.f('ix_visit_status_history_visit_id'), 'visit_status_history', ['visit_id'], unique=False)
    op.create_table('lab_results',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('lab_request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('technician_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('result_value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('result_unit', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('reference_range', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lab_request_id'], ['lab_requests.id'], name=op.f('lab_results_lab_request_id_fkey')),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], name=op.f('lab_results_technician_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('lab_results_pkey'))
    )
    op.create_table('dispensations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('prescription_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pharmacist_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pharmacist_id'], ['users.id'], name=op.f('dispensations_pharmacist_id_fkey')),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], name=op.f('dispensations_prescription_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('dispensations_pkey'))
    )
    op.create_table('idempotency_keys',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('endpoint', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('request_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('response_body', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('idempotency_keys_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('idempotency_keys_pkey'))
    )
    # ### end Alembic commands ###
