"""add_clinic_profile_fields

Revision ID: 8e92d7b47ef4
Revises: 1d7dafaac16d
Create Date: 2026-01-20 18:22:58.968287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '8e92d7b47ef4'
down_revision: Union[str, Sequence[str], None] = '1d7dafaac16d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinics', sa.Column('logo_url', sa.String(length=512), nullable=True))
    op.add_column('clinics', sa.Column('address', sa.String(length=512), nullable=True))
    op.add_column('clinics', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('clinics', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('clinics', sa.Column('timezone', sa.String(length=64), nullable=True))
    op.add_column('clinics', sa.Column('description', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinics', 'description')
    op.drop_column('clinics', 'timezone')
    op.drop_column('clinics', 'email')
    op.drop_column('clinics', 'phone')
    op.drop_column('clinics', 'address')
    op.drop_column('clinics', 'logo_url')
    # ### end Alembic commands ###
