"""add status to lab_requests

Revision ID: bc08b2efdd7d
Revises: 71540f7a0ab0
Create Date: 2026-01-03 08:53:02.322368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc08b2efdd7d'
down_revision: Union[str, Sequence[str], None] = '71540f7a0ab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    op.execute(f"DROP INDEX IF EXISTS {op.f('ix_visit_status_history_visit_id')}")
    op.execute("DROP TABLE IF EXISTS visit_status_history")
    op.execute("DROP TABLE IF EXISTS consultations")
    op.execute("DROP TABLE IF EXISTS idempotency_keys")
    op.execute("DROP TABLE IF EXISTS lab_results")
    op.execute("DROP TABLE IF EXISTS dispensations")

    if "lab_requests" in inspector.get_table_names():
        labrequeststatus = sa.Enum(
            "PENDING",
            "COMPLETED",
            "CANCELLED",
            name="labrequeststatus",
        )
        if conn.dialect.name != "sqlite":
            labrequeststatus.create(conn, checkfirst=True)

        columns = {col["name"] for col in inspector.get_columns("lab_requests")}
        if "status" not in columns:
            op.add_column(
                "lab_requests",
                sa.Column("status", labrequeststatus, nullable=False),
            )
        if "completed_at" not in columns:
            op.add_column(
                "lab_requests",
                sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
            )

        existing_indexes = {ix["name"] for ix in inspector.get_indexes("lab_requests")}
        status_index = op.f("ix_lab_requests_status")
        visit_index = op.f("ix_lab_requests_visit_id")
        if status_index not in existing_indexes:
            op.create_index(status_index, "lab_requests", ["status"], unique=False)
        if visit_index not in existing_indexes:
            op.create_index(visit_index, "lab_requests", ["visit_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lab_requests_visit_id'), table_name='lab_requests')
    op.drop_index(op.f('ix_lab_requests_status'), table_name='lab_requests')
    op.drop_column('lab_requests', 'completed_at')
    op.drop_column('lab_requests', 'status')
    op.create_table('dispensations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('prescription_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pharmacist_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pharmacist_id'], ['users.id'], name=op.f('dispensations_pharmacist_id_fkey')),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], name=op.f('dispensations_prescription_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('dispensations_pkey'))
    )
    op.create_table('lab_results',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('lab_request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('technician_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('result_value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('result_unit', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('reference_range', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lab_request_id'], ['lab_requests.id'], name=op.f('lab_results_lab_request_id_fkey')),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], name=op.f('lab_results_technician_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('lab_results_pkey'))
    )
    op.create_table('idempotency_keys',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('endpoint', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('request_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('response_body', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('idempotency_keys_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('idempotency_keys_pkey'))
    )
    op.create_table('consultations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('visit_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('vitals', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('presenting_complaints', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('diagnosis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name=op.f('consultations_doctor_id_fkey')),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], name=op.f('consultations_visit_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('consultations_pkey')),
    sa.UniqueConstraint('visit_id', name=op.f('uq_consultation_visit'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('visit_status_history',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('visit_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('from_status', postgresql.ENUM('REGISTERED', 'TRIAGED', 'IN_CONSULTATION', 'LAB_REQUESTED', 'LAB_COMPLETED', 'PHARMACY_PENDING', 'COMPLETED', 'CANCELLED', name='visitstatus'), autoincrement=False, nullable=False),
    sa.Column('to_status', postgresql.ENUM('REGISTERED', 'TRIAGED', 'IN_CONSULTATION', 'LAB_REQUESTED', 'LAB_COMPLETED', 'PHARMACY_PENDING', 'COMPLETED', 'CANCELLED', name='visitstatus'), autoincrement=False, nullable=False),
    sa.Column('changed_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('visit_status_history_changed_by_fkey')),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], name=op.f('visit_status_history_visit_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('visit_status_history_pkey'))
    )
    op.create_index(op.f('ix_visit_status_history_visit_id'), 'visit_status_history', ['visit_id'], unique=False)
    # ### end Alembic commands ###
