"""add email to users

Revision ID: ea00d335a74e
Revises: 9c72471e6e3e
Create Date: 2025-12-30 15:14:25.571961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea00d335a74e'
down_revision: Union[str, Sequence[str], None] = '9c72471e6e3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    dialect = bind.dialect.name
    inspector = sa.inspect(bind)
    fk_names = {
        fk.get("name")
        for fk in inspector.get_foreign_keys("users")
        if fk.get("name")
    }

    if dialect == "sqlite":
        with op.batch_alter_table("users") as batch:
            batch.add_column(sa.Column("email", sa.String(length=255), nullable=True))
            batch.add_column(sa.Column("password_hash", sa.String(length=255), nullable=True))
        op.execute(
            "UPDATE users SET email = 'unknown+' || id || '@invalid.local' "
            "WHERE email IS NULL"
        )
        op.execute(
            "UPDATE users SET password_hash = 'migrated-' || id "
            "WHERE password_hash IS NULL"
        )
        with op.batch_alter_table("users") as batch:
            batch.alter_column("email", nullable=False)
            batch.alter_column("password_hash", nullable=False)
            batch.create_index(op.f("ix_users_email"), ["email"], unique=True)
            if op.f("users_clinic_id_fkey") in fk_names:
                batch.drop_constraint(op.f("users_clinic_id_fkey"), type_="foreignkey")
            batch.create_foreign_key(
                "users_clinic_id_fkey",
                "clinics",
                ["clinic_id"],
                ["id"],
                ondelete="CASCADE",
            )
    else:
        op.add_column("users", sa.Column("email", sa.String(length=255), nullable=True))
        op.add_column("users", sa.Column("password_hash", sa.String(length=255), nullable=True))
        op.execute(
            "UPDATE users SET email = 'unknown+' || id::text || '@invalid.local' "
            "WHERE email IS NULL"
        )
        op.execute(
            "UPDATE users SET password_hash = 'migrated-' || id::text "
            "WHERE password_hash IS NULL"
        )
        op.alter_column("users", "email", nullable=False)
        op.alter_column("users", "password_hash", nullable=False)
        op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
        if op.f("users_clinic_id_fkey") in fk_names:
            op.drop_constraint(op.f("users_clinic_id_fkey"), "users", type_="foreignkey")
        op.create_foreign_key(
            "users_clinic_id_fkey",
            "users",
            "clinics",
            ["clinic_id"],
            ["id"],
            ondelete="CASCADE",
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    dialect = bind.dialect.name
    if dialect == "sqlite":
        with op.batch_alter_table("users") as batch:
            batch.drop_constraint("users_clinic_id_fkey", type_="foreignkey")
            batch.create_foreign_key(
                "users_clinic_id_fkey",
                "clinics",
                ["clinic_id"],
                ["id"],
            )
            batch.drop_index(op.f("ix_users_email"))
            batch.drop_column("password_hash")
            batch.drop_column("email")
    else:
        op.drop_constraint("users_clinic_id_fkey", "users", type_="foreignkey")
        op.create_foreign_key("users_clinic_id_fkey", "users", "clinics", ["clinic_id"], ["id"])
        op.drop_index(op.f("ix_users_email"), table_name="users")
        op.drop_column("users", "password_hash")
        op.drop_column("users", "email")
    # ### end Alembic commands ###
