// /projects/clinic-monorepo/clinic-app/src/shared/enums.ts
export enum UserRole {
  RECEPTION = 'RECEPTION',
  CASHIER = 'CASHIER',
  ACCOUNTANT = 'ACCOUNTANT',
  CMD = 'CMD',
  DOCTOR = 'DOCTOR',
  LAB = 'LAB',
  LAB_TECH = 'LAB_TECH',
  LAB_SCIENTIST = 'LAB_SCIENTIST',
  LAB_SUPERVISOR = 'LAB_SUPERVISOR',
  LAB_MANAGER = 'LAB_MANAGER',
  PHARMACY = 'PHARMACY',
  PHARMACY_HOD = 'PHARMACY_HOD',
  PHARMACY_STORE_OFFICER = 'PHARMACY_STORE_OFFICER',
  CHEW = 'CHEW',
  MIDWIFE = 'MIDWIFE',
  ADMIN = 'ADMIN',
  CLINIC_ADMIN = 'CLINIC_ADMIN',
  SYSTEM = 'SYSTEM',
}

export enum VisitStatus {
  REGISTERED = 'REGISTERED',
  // Deprecated legacy value. Triage progression is tracked by VisitTriageState.
  TRIAGED = 'TRIAGED',
  IN_CONSULTATION = 'IN_CONSULTATION',
  LAB_REQUESTED = 'LAB_REQUESTED',
  LAB_COMPLETED = 'LAB_COMPLETED',
  PHARMACY_PENDING = 'PHARMACY_PENDING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum VisitServiceLine {
  OPD = 'OPD',
  ANC = 'ANC',
  MATERNITY = 'MATERNITY',
}

export enum ServiceLineKind {
  GENERAL = 'GENERAL',
  LAB_UNIT = 'LAB_UNIT',
  PHARMACY_UNIT = 'PHARMACY_UNIT',
}

export enum VisitTriageState {
  NOT_REQUIRED = 'NOT_REQUIRED',
  PENDING = 'PENDING',
  TRIAGED = 'TRIAGED',
}

export enum PrescriptionStatus {
  ISSUED = 'ISSUED',
  DISPENSED = 'DISPENSED',
  CANCELLED = 'CANCELLED',
  EXTERNALLY_FULFILLED = 'EXTERNALLY_FULFILLED',
}

export enum PrescriptionFulfillmentType {
  DISPENSED_IN_HOUSE = 'DISPENSED_IN_HOUSE',
  DISPENSED_EXTERNAL = 'DISPENSED_EXTERNAL',
}

export enum PharmacyPrescriptionWorkflowStatus {
  ASSIGNED = 'ASSIGNED',
  AWAITING_PAYMENT_CLEARANCE = 'AWAITING_PAYMENT_CLEARANCE',
  READY_TO_DISPENSE = 'READY_TO_DISPENSE',
  PARTIALLY_DISPENSED = 'PARTIALLY_DISPENSED',
  IN_DISPENSE = 'IN_DISPENSE',
  DISPENSED = 'DISPENSED',
  REASSIGNED = 'REASSIGNED',
  CANCELLED = 'CANCELLED',
  EXTERNALLY_FULFILLED = 'EXTERNALLY_FULFILLED',
}

export enum PharmacyExceptionAuthorizationType {
  NONE = 'NONE',
  NHIS_COVERED = 'NHIS_COVERED',
  EMERGENCY_OVERRIDE = 'EMERGENCY_OVERRIDE',
  HOD_AUTHORIZED_OVERRIDE = 'HOD_AUTHORIZED_OVERRIDE',
}

export enum PurposeOfUse {
  TREATMENT = 'TREATMENT',
  OPERATIONS = 'OPERATIONS',
  EMERGENCY = 'EMERGENCY',
  AUDIT = 'AUDIT',
  BILLING = 'BILLING',
  SECURITY = 'SECURITY',
}
