#!/usr/bin/env bash
set -euo pipefail

# Shared local development defaults for this repository.
# Override any variable before sourcing this file when needed.

ROOT_DIR="${ROOT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"

PROJECT_SLUG="${PROJECT_SLUG:-his_monorepo}"

BACKEND_HOST="${BACKEND_HOST:-127.0.0.1}"
BACKEND_PORT="${BACKEND_PORT:-8110}"

FRONTEND_HOST="${FRONTEND_HOST:-127.0.0.1}"
FRONTEND_PORT="${FRONTEND_PORT:-3310}"

DB_HOST="${DB_HOST:-127.0.0.1}"
DB_PORT="${DB_PORT:-5432}"
DB_ADMIN_USER="${DB_ADMIN_USER:-postgres}"
DB_NAME="${DB_NAME:-${PROJECT_SLUG}_db}"
DB_USER="${DB_USER:-${PROJECT_SLUG}_user}"
DB_PASSWORD="${DB_PASSWORD:-${PROJECT_SLUG}_password}"

DATABASE_URL="${DATABASE_URL:-postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}}"
NEXT_PUBLIC_API_URL="${NEXT_PUBLIC_API_URL:-http://${BACKEND_HOST}:${BACKEND_PORT}/api}"
E2E_BASE_URL="${E2E_BASE_URL:-http://${FRONTEND_HOST}:${FRONTEND_PORT}}"
E2E_API_BASE_URL="${E2E_API_BASE_URL:-http://${BACKEND_HOST}:${BACKEND_PORT}/api}"

CORS_ORIGINS="${CORS_ORIGINS:-[\"http://localhost:${FRONTEND_PORT}\",\"http://127.0.0.1:${FRONTEND_PORT}\"]}"

export ROOT_DIR PROJECT_SLUG BACKEND_HOST BACKEND_PORT FRONTEND_HOST FRONTEND_PORT
export DB_HOST DB_PORT DB_ADMIN_USER DB_NAME DB_USER DB_PASSWORD DATABASE_URL
export NEXT_PUBLIC_API_URL E2E_BASE_URL E2E_API_BASE_URL CORS_ORIGINS
